version: '3'

services:
  main:
    image: translate-typeform
    build: .
    command: |
      sh -c '
        echo "Running tests..."
        npm install
        npm test
      '
    volumes:
      - ./:/app
