version: '3'

services:
  main:
    image: node:12.22.8-alpine
    working_dir: /app
    command: |
      sh -c '
        echo "Running tests..."
        npm install
        if [ "${IS_CI}" = "" ]
        then
          npm test
        fi
        npm run test-ci
      '
    volumes:
      - ./:/app
